Control the nav_filter model with a parameter
Zubax/zubax_gnss pull request #9
Opened 2016-10-01 01:49 UTC by WickedShell

Also updates default value of the nav_filter from Airborne_2g to Airborne_4g. (APM testing shows that Airborne_4g has less filtering on the data, and the minimum amount of filtering is desired).

Also updates the list of DynModels to acknowledge that 9 is the dynamic model for wrists, its only used in newer GPS firmware, but the GPS chip can be upgraded to that firmware.

2016-10-02 17:37 UTC, pavel-kirienko requested changes
Thanks Michael, please see my feedback.

2016-10-02 17:37 UTC, pavel-kirienko commented on firmware/src/board/ublox.cpp
> +        cfg_.nav_filter_model = std::max(cfg_.nav_filter_model, static_cast<uint32_t>(msg::CFG_NAV5::DynModel::Portable));
I suggest to define constants next to `DynModel` constraining the range of the enumeration values, e.g. 'DynModelMin = 0', `DynModelMax = 9`. These same constants should also be used in the configuration parameter range definition. Leaving it as-is makes the code not future-proof.

2016-10-02 17:37 UTC, pavel-kirienko commented on firmware/src/board/ublox.hpp
> +    uint32_t nav_filter_model = static_cast<uint32_t>(msg::CFG_NAV5::DynModel::Airborne_4g);
One should take advantage of the C++ type system whenever possible, as that results in safer and more reliable code. Here I would suggest to replace `uint32_t` with `msg::CFG_NAV5::DynModel`. Type casts in other places will need to be updated accordingly.

2017-03-19 09:35 UTC, pavel-kirienko commented on firmware/src/gnss.cpp
> +os::config::Param<unsigned> param_gnss_nav_filter_model("gnss.nav_filter_model", 8, 0, 9);
Sorry that it is not immediately clear, but maximum parameter name length must not exceed 16 characters. This limitation is imposed by UAVCAN-MAVLink parameter bridge.

2017-03-19 09:36 UTC, pavel-kirienko commented
Hey @WickedShell! Could you please review my feedback? We're releasing firmware version 4 soon, would be great to merge your changes in too.

2017-03-29 00:13 UTC, WickedShell commented
Sorry missed the most recent round of comments in my inbox. I'll try and get some time allocated within the near future to finish fixing this up. (I encountered some problems with my Zubax that I suspect are cabling but haven't been able to debug it yet. My babel came in so hopefully with that I can get it going again).

2017-03-29 00:37 UTC, pavel-kirienko commented
No worries. We have time until late April to merge this and ship with the newest batch of hardware ;)

2017-03-29 00:38 UTC, pavel-kirienko commented
A cool bootloader is coming up too, supports USB, UART, and CAN, so upgrading in the field will be much easier.

2017-04-10 06:32 UTC, WickedShell commented
@pavel-kirienko I pushed fixes (apparently I'd actually done 90% of the requested changes). Due to a slight cabling problem here I haven't flashed it yet to validate that it all still behaves correctly, but wanted to get it pushed up first, so it stopped languishing. Will hopefully find the needed cables (and time) to validate this the rest of the way tomorrow.

2017-04-10 09:56 UTC, pavel-kirienko requested changes
Thanks @WickedShell! Added some comments.

2017-04-10 09:56 UTC, pavel-kirienko commented on firmware/src/board/ublox_msg.hpp
> +#define GNSS_DYN_MODEL_DEFAULT 8
Macros can only be used for purposes of conditional compilation, and they are never allowed within the namespace scope. Here please replace that with this:

```c++
static constexpr U1 DynModelMin = 0;
static constexpr U1 DynModelMax = 8;
```

The default should not be declared in the driver, this violates the separation of concerns. Please move it to the definition of the configuration parameter.

2017-04-10 09:56 UTC, pavel-kirienko commented on firmware/src/board/ublox.cpp
> +        os::lowsyslog("GNSS Filter Model: %02x\n", int(nav5->dynModel));
Please add a prefix `ublox: ` before the log line.

2017-04-10 09:56 UTC, pavel-kirienko commented on firmware/src/board/ublox.cpp
> +    if (static_cast<uint8_t>(cfg_.nav_filter_model) == 1) {
`std::uint8_t`

2017-04-10 09:56 UTC, pavel-kirienko commented on firmware/src/board/ublox.cpp
> +        cfg_.nav_filter_model = std::max(cfg_.nav_filter_model, msg::CFG_NAV5::DynModel::Portable);
Perhaps you intended to use your `DynModelMin`/`DynModelMax` here?

2017-07-26 14:05 UTC, pavel-kirienko commented
@WickedShell should we still keep this open?

2017-11-19 11:42 UTC, closed without merging